version: '2'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data
  db:
    image: mysql:8.0.15
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: 1qaz2wsx
      MYSQL_DATABASE: testdb
    command: [
      --character-set-server=utf8mb4,
      --collation-server=utf8mb4_general_ci,
      --default-storage-engine=innodb
    ]
