@startuml

() "public:8443"
() "private:22"
() "private:13306"
() "private:6379"

cloud "Microsoft Azure" {
    package "VM-No1" {

    () "port-vmdc:13306"
    () "port-vadc:8443"
    () "port-vrdc:6379"
    () "port-v:22"

    node "mysql-docker-container" {
        () "port-mdc:3306"
        database "mysql8" {
            () "port-mdcm:3306"
        }
    }

    node "app-docker-container" {
        component "triela-application"{
            () "port-adct:13306"
            () "port-rdct:6379"
            () "port-adct:8443"
        }
        () "port-adc:8443"
    }

    node "redis-docker-container" {
        component "Redis" {
            () "port-r:6379"
        }
        () "port-rdc:6379"
    }
}

[public:8443] <--> [port-vadc:8443]
[private:13306] <-left-> [port-vmdc:13306]
[private:22] <--> [port-v:22]
[private:6379] <-left-> [port-vrdc:6379]

[port-vrdc:6379] <--> [port-rdc:6379]
[port-vrdc:6379] <--> [port-rdct:6379]
[port-vadc:8443] <--> [port-adc:8443]
[port-vmdc:13306] <-down-> [port-mdc:3306]


[port-adc:8443] <--> [port-adct:8443]
[port-rdc:6379] <-> [port-r:6379]

[port-mdc:3306] <-> [port-mdcm:3306]
[port-vmdc:13306] -up-> [port-adct:13306]

@enduml
