server:
  port: 8443
  servlet:
    context-path: /
security:
  oauth2:
    client:
      # client-id: [from triela-private]
      # client-secret: [from triela-private]
      access-token-uri: https://github.com/login/oauth/access_token
      user-authorization-uri: https://github.com/login/oauth/authorize
      client-authentication-scheme: form
      scope: email
    resource:
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
      prefer-token-info: false

spring:
  profiles:
    active: dev
  cache:
    cache-names: dllCache
    caffeine:
      spec: maximumSize=1000000, expireAfterWrite=3600s

github:
  client:
    client-id: xxxxxxxxxxxxxx
    client-secret: xxxxxxxxxxxxxxxxxxxxxxxx
    access-token-uri: https://github.com/login/oauth/access_token
    user-authorization-uri: https://github.com/login/oauth/authorize
    client-authentication-scheme: form
  resource:
    user-info-uri: https://api.github.com/user
    prefer-token-info: false