server:
  ssl:
    key-store: app/triela.pkcs12
    key-store-password: 1qaz2wsx
    keyStoreType: PKCS12
    keyAlias: triela
spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:13306/mydb?characterEncoding=UTF-8&serverTimezone=JST # test
    username: root
    password: mysql
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10