server:
  ssl:
    key-store: ../triela-private/triela.tk/triela.pkcs12
    #key-store-password: [from triela-private]
    keyStoreType: PKCS12
    keyAlias: triela
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mydb?characterEncoding=UTF-8&serverTimezone=JST
    username: root
    #password: [from triela-private]
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
