server:
  ssl:
    key-store: ../triela-private/triela.ml/triela.pkcs12
    #key-store-password: [from triela-private]
    keyStoreType: PKCS12
    keyAlias: triela
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:53306/mydb?characterEncoding=UTF-8&serverTimezone=JST
    username: root
    #password: [from triela-private]
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  session:
    store-type: redis
  redis:
    host: localhost
    port: 46379
  security:
    oauth2:
      client:
        registration:
          github:
            redirect-uri: https://triela.ml:8443/login/oauth2/code/github
