server:
  port: 8443
  servlet:
    context-path: /
security:
  oauth2:
    client:
      client-id: b812ba0e80fcaaea1899
      client-secret: ed5ef05f3482c8e1d4404cd28d5fc0187dd8cad1
      access-token-uri: https://github.com/login/oauth/access_token
      user-authorization-uri: https://github.com/login/oauth/authorize
      client-authentication-scheme: form
    resource:
      user-info-uri: https://api.github.com/user
      prefer-token-info: false
    sso:
      login-path: /login
spring:
  profiles:
    active: dev
  cache:
    cache-names: dllCache
    caffeine:
      spec: maximumSize=1000000, expireAfterWrite=3600s

