server:
  ssl:
    key-store: /etc/trielaprivate/triela.pkcs12
    keyStoreType: PKCS12
    #key-store-password: [from triela-private]
    keyAlias: triela
spring:
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/mydb?characterEncoding=UTF-8&serverTimezone=JST&allowPublicKeyRetrieval=true&useSSL=false
    username: gnagaoka
    #password: [from triela-private]
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  session:
    store-type: redis
  redis:
    host: session.dpsihg.0001.apne1.cache.amazonaws.com
    port: 6379
