spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:53306/testdb?characterEncoding=UTF-8&serverTimezone=JST
    username: root
    password: 1qaz2wsx
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  session:
    store-type: redis
  redis:
    host: localhost
    port: 46379
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: c3b647914aed0ff081da
            # client-secret: from env
            redirect-uri: http://local.triela.popush.cloud/login/oauth2/code/github
