server:
  ssl:
    key-store: src/main/resources/triela.pkcs12
    key-store-password: 1qaz2wsx
    keyStoreType: PKCS12
    keyAlias: triela
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mydb?characterEncoding=UTF-8&serverTimezone=JST
    username: root
    password: 1qaz2wsx
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10