spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/mydb?characterEncoding=UTF-8&serverTimezone=JST # test
    username: root
    password: 1qaz2wsx
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10