server:
  port: 8080
  servlet:
    context-path: /
security:
  oauth2:
    client:
      client-id: b812ba0e80fcaaea1899
      client-secret: ed5ef05f3482c8e1d4404cd28d5fc0187dd8cad1
      access-token-uri: https://github.com/login/oauth/access_token
      user-authorization-uri: https://github.com/login/oauth/authorize
      client-authentication-scheme: form
    resource:
      user-info-uri: https://api.github.com/user
      prefer-token-info: false
    sso:
      login-path: /login
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mydb?characterEncoding=UTF-8&serverTimezone=JST # test
    username: root
    password: 1qaz2wsx
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10