spring:
  datasource:
    url: jdbc:mysql://mysql/mydb?characterEncoding=UTF-8&serverTimezone=JST&allowPublicKeyRetrieval=true&useSSL=false
    username: gnagaoka
    #password: from secret
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  session:
    store-type: redis
  redis:
    host: redis
    port: 6379
  security:
    oauth2:
      client:
        registration:
          github:
            # client-id: from secret
            # client-secret: from secret
            redirect-uri: https://triela.popush.cloud/login/oauth2/code/github
