server:
  port: 80
  servlet:
    context-path: /
spring:
  profiles:
    active: dev
  cache:
    cache-names: dllCache
    caffeine:
      spec: maximumSize=1000000, expireAfterWrite=3600s
  security:
    oauth2:
      client:
        registration:
          github:
            scope:
              - read:repo
distribution:
  s3-bucket-region: ap-north-east-1
  s3-bucket-name: triela-file
  cloud-front-domain-name: d3fxmsw7mhzbqi.cloudfront.net

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true

# [webhook_secret]

management:
  info:
    git:
      mode: full

