@startuml

() "triela.tk:8443"
() "d3mq2c18xv0s3o.cloudfront.net:443"
() "private:22"
() "private:3306"


cloud "AWS" {

    package "CloudFront"{
        component "distribution"
    }

    package "RDS"{
        database "mysql8" {
            () "port-mysql:3306"
        }
    }

    package "VM-No1" {
    () "EIP:8443"
    () "port-v:22"

    node "app-docker-container" {

        component "triela-application"{
            () "port-adct:3306"
            () "port-adct:8443"

            () "app-env"
        }
    }

    node "private-docker-container" {
        file "credential and env"
    }
}

[d3mq2c18xv0s3o.cloudfront.net:443] --> [distribution]
[distribution] --> [EIP:8443]
[triela.tk:8443] ---> [EIP:8443]
[private:22] ---> [port-v:22]

[EIP:8443] --> [port-adct:8443]

[port-adct:3306] --> [port-mysql:3306]
[private:3306] -----> [port-mysql:3306]

[credential and env] -up-> [app-env]

@enduml
