@startuml

participant User
participant Paradox_launcher
participant exe
participant version.dll
participant autoupdate64.bat
participant dllautoupdater.exe
participant Plugin64.dll
participant claes.exe
participant contentserver

activate contentserver

activate User
User -> Paradox_launcher: run

activate Paradox_launcher
Paradox_launcher -> exe: call application

activate exe
exe -> version.dll: dllmain

deactivate Paradox_launcher

activate version.dll
version.dll -> autoupdate64.bat : createprocess

activate autoupdate64.bat
autoupdate64.bat -> dllautoupdater.exe : run

activate dllautoupdater.exe
dllautoupdater.exe -> contentserver : exe_md5,dll_md5

dllautoupdater.exe <- contentserver : download Plugin64.dll

dllautoupdater.exe --> Plugin64.dll : Plugin64.dll update
dllautoupdater.exe <-- Plugin64.dll : success

autoupdate64.bat <- dllautoupdater.exe
deactivate dllautoupdater.exe

version.dll <- autoupdate64.bat
deactivate autoupdate64.bat

version.dll -> version.dll : injection Plugin64.dll

exe <-- Plugin64.dll

exe <- version.dll

exe -> Plugin64.dll : dll main
activate Plugin64.dll

Plugin64.dll -> claes.exe : call

activate claes.exe
claes.exe -> contentserver : check newest mod

claes.exe <- contentserver : download new mods

claes.exe -> claes.exe : Update mods in\n documents folder

Plugin64.dll <- claes.exe

deactivate claes.exe


exe <- Plugin64.dll: patches multi byte fix

User <- exe : show load image


@enduml