@startuml

() "public:8443"
() "private:22"
() "private:13306"
() "private:6379"

cloud "Microsoft Azure" {
    package "VM-No1" {

    () "port-vmdc:13306"
    () "port-vadc:8443"
    () "port-vrdc:6379"
    () "port-v:22"

    node "mysql-docker-container" {
        database "mysql8" {
            () "port-mysql:3306"
        }
        () "mysql-data"
    }

    node "app-docker-container" {

        component "triela-application"{
            () "port-adct:13306"
            () "port-rdct:6379"
            () "port-adct:8443"

            () "app-env"
        }
    }

    node "redis-docker-container" {
        () "redis-env"
        component "Redis" {
            () "port-redis:6379"
        }
    }

    node "private-docker-container" {
        file "credential and env"
        file "data"
    }
}

[public:8443] <--> [port-vadc:8443]
[private:13306] <----> [port-vmdc:13306]
[private:22] <--> [port-v:22]
[private:6379] <--> [port-vrdc:6379]

[port-vrdc:6379] <--> [port-rdct:6379]

[port-adct:13306] <--> [port-vmdc:13306]

[port-vadc:8443] <--> [port-adct:8443]
[port-vrdc:6379] <--> [port-redis:6379]

[port-vmdc:13306] --> [port-mysql:3306]

[credential and env] -up-> [app-env]
[data] <->[mysql-data]

@enduml
